-- Q.1) what is the total revenue generated by male vs female customers
select gender,sum(purchase_amount) as revenue
from customers
group by gender;

-- Q.2) Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount 
from customers
where discount_applied = 'Yes'
and purchase_amount >= (select avg(purchase_amount) from customers);

-- Q.3) Which are the top 5 products with highest average review rating?
select item_purchased, round(avg(review_rating::numeric),2) as avg_rating
from customers
group by item_purchased
order by avg_rating desc
limit 5;

-- Q.4) compare the average purchase amount between standard and avg shipping?

select shipping_type, round(avg(purchase_amount),2)
from customers
where shipping_type in ('Standard', 'Express')
group by shipping_type;

-- Q.5) Do subscribed spend more ? compare average spend and total revenue between subscribers and non subscribers

select subscription_status, count(*) as total_customers,
round(avg(purchase_amount),2) as avg_spend,
sum(purchase_amount) as total_revenue
from customers
group by subscription_status
order by total_revenue, avg_spend desc;

-- which 5 products have the highest percentage of purchases with discounts applied ?
select item_purchased, 
round(100.0 * sum(case when upper(discount_applied) = 'YES' then 1 else 0 end)/count(*),2) as discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5;



-- segments customers into new, returning and loyal based on their total number of previour order
with customer_type as (
select customer_id, previous_purchases,
case 
when previous_purchases=1 then 'New'
when previous_purchases between 2 and 10 then 'Returning'
else 'Loyal'
end as customer_segment
from customers
)

select customer_segment, count(*) as no_of_customers
from customer_type
group by customer_segment;

-- what are the top 3 most purchased product within each category
with item_count as (
select category, item_purchased, count(customer_id) as total_orders,
row_number()over(partition by category order by count(customer_id) desc) as item_rank
from customers
group by category,item_purchased
)
select category, item_purchased, total_orders
from item_count
where item_rank<=3;


-- are customers who are repeat buyers (more than 5 times) also likely to subscribe?
select subscription_status, count(customer_id)
from customers
where previous_purchases >5
group by subscription_status;


-- what is the revenue contribution by the each age group?
select age_group, sum(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue desc;

 
select * from customers
limit 5;

